quarkus:
  http:
    port: 8080
  websockets-next:
    server:
      propagate-subprotocol-headers: true
      supported-subprotocols: v12.stomp,v11.stomp

reactive-stomp:
  heartbeat: 1000, 1000
  messaging:
    broker:
      regex: /topic.*
    message-endpoint:
      regex: /endpoint.*
  stomp:
    ackPeriod: 1000